seed: 42
data_root: /workspace/data
checkpoint_dir: /workspace/checkpoints_final

batch_size: 64
epochs: 20

num_layers: 7
hidden_dim: 256
dropout: 0.1
use_virtual_node: true

lr: 0.0003
scheduler_step: 6
scheduler_gamma: 0.5